### ISSUE TITLE
Error to run nexus after added the parameters on nexus-core-feature-3.8.0-02-features.xml 

### ISSUE THREAD

**Issue by zyriuse75** [sonatype-nexus-community/nexus-repository-helm#17] opened 2018-09-26 14:24 UTC
* **What are you trying to do?**
 I  trying to setup the plugin. 

I've added on : 
> nexus/latest/system/org/sonatype/nexus/assemblies/nexus-core-feature/3.8.0-02/nexus-core-feature-3.8.0-02-features.xml 

The lines below as you said on your procedure.
`
<feature version="3.8.0.02" prerequisite="false" dependency="false">nexus-task-log-cleanup</feature> <feature prerequisite="false" dependency="false">nexus-repository-helm</feature> `

When i start nexus  **./nexus run**
i'get the error below . I've checked the owner of the directory , the name of the directory and everything is good 
```
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-core-feature; type=karaf.feature; version=0; filter:="(&(osgi.identity=nexus-core-feature)(type=karaf.feature)(version>=0.0.0))" [caused by: Unable to resolve nexus-core-feature/3.8.0.02: missing requirement [nexus-core-feature/3.8.0.02] osgi.identity; osgi.identity=nexus-repository-helm; type=karaf.feature; version="[0.0.4,0.0.4]" [caused by: Unable to resolve nexus-repository-helm/0.0.4: missing requirement [nexus-repository-helm/0.0.4] osgi.identity; osgi.identity=org.sonatype.repository.nexus-repository-helm; type=osgi.bundle; version="[0.0.4,0.0.4]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.repository.nexus-repository-helm/0.0.4: missing requirement [org.sonatype.repository.nexus-repository-helm/0.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.google.common.base)(version>=25.0.0))"]]]
        at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:259)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
2018-09-26 15:07:37,905+0200 DEBUG [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender - BundleEvent STOPPING - org.sonatype.nexus.extender
2018-09-26 15:07:37,944+0200 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Uptime: 14 seconds and 502 milliseconds
2018-09-26 15:07:37,946+0200 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Stop KERNEL
```
nexus : 3.8.0.-02
Red Hat Enterprise Linux Server release 6.6

**Comment by loverto** [comment] 2018-09-27 23:15
Upgrade your nexus to latest

**Comment by DarthHater** [comment] 2018-09-28 19:47
Yeah, this will not work against an older version of Nexus Repository. I can't say for sure which it would fail on, but please use 3.13 or higher for now.

**Comment by DarthHater** [comment] 2018-09-28 19:47
@zyriuse75 or @loverto we should probably add a documentation note about this, if either of you wants to send a PR I'll keep this issue open to track that!

**Comment by au-hao** [comment] 2018-10-31 14:41
I am using nexus 3.13 and having the same issue:

**Comment by DarthHater** [comment] 2018-11-01 00:38
I'll give it a twirl!

**Comment by DarthHater** [comment] 2018-11-01 01:01
Pretty sure I know what the issue is. I'm going to make some updates to get Helm working with 3.14.0-04 and I'll also update some instructions to get it good to go with 3.13.0-01

**Comment by nicosto** [comment] 2019-01-09 00:10
Hi, any update on the fix for 3.14?

**Comment by DarthHater** [comment] 2019-01-09 00:12
Lemme spin up a branch, I'll push it up if you'll test it :)

**Comment by nicosto** [comment] 2019-01-09 00:14
Happy to give a spin

**Comment by nicosto** [comment] 2019-01-09 00:43
@DarthHater  I can confirm that 0.0.7 is working on my nexus 3.14.0-04.
Thanks for the quick fix on this.

**Comment by bhamail** [comment] 2019-07-24 18:34
Closing as fixed. There's also some shiny new releases available now.

**Closed by bhamail** 2019-07-24 18:34 UTC
